[package]
name = "spellbook"
version = "0.1.0"
authors = ["Bob Henkel <bob.henkel@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusqlite = "0.21.0"
